---
name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: uclahs-cds/tool-R-CMD-check-action@renv
